import { neon } from '@neondatabase/serverless';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
const sql=neon(process.env.DATABASE_URL);
const JWT_SECRET=process.env.JWT_SECRET;
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw new Error('Login diperlukan.');return jwt.verify(h.slice(7),JWT_SECRET)}
function token(u){return jwt.sign({id:u.id,username:u.username,role:u.role},JWT_SECRET,{expiresIn:'7d'})}
function publicQ(q,teacher=false){return {id:q.id,topic:q.topic,level:q.level,q:q.question_text,opts:q.options,source:q.source,type:'mcq',...(teacher?{ans:q.answer_index,expl:q.explanation}:{})}}
async function seedDefaultExam(userId){let e=await sql`select * from exams where title='Simulasi CBT MatematikaPakade' limit 1`;if(e.length)return e[0];let qs=await sql`select id from questions order by created_at asc limit 25`;let x=await sql`insert into exams(title,duration_minutes,question_count,status,created_by) values('Simulasi CBT MatematikaPakade',25,${Math.min(25,qs.length)},'published',${userId}) returning *`;for(let i=0;i<qs.length;i++)await sql`insert into exam_questions(exam_id,question_id,position) values(${x[0].id},${qs[i].id},${i+1})`;return x[0]}
export default async function handler(req,res){try{const u=new URL(req.url,'http://localhost');const p=u.pathname.replace(/^\/api/,'')||'/';if(req.method==='GET'&&p==='/health')return json(res,200,{ok:true,service:'MatematikaPakade CBT v6'});
if(req.method==='POST'&&p==='/auth/login'){const b=await body(req),role=b.role==='teacher'?'teacher':'student';if(!b.username?.trim())return json(res,400,{error:'Username wajib diisi.'});if(role==='teacher'&&b.teacherCode!==process.env.TEACHER_CODE)return json(res,401,{error:'Kode guru salah.'});let rows=await sql`select * from users where lower(username)=lower(${b.username.trim()}) limit 1`;let user=rows[0];if(!user){const hash=await bcrypt.hash(crypto.randomUUID(),12);user=(await sql`insert into users(username,role,display_name,password_hash) values(${b.username.trim()},${role},${b.username.trim()},${hash}) returning *`)[0]}else if(user.role!==role)return json(res,403,{error:'Peran akun tidak sesuai.'});return json(res,200,{token:token(user),user:{id:user.id,username:user.username,role:user.role}})}
if(req.method==='POST'&&p==='/auth/logout')return json(res,200,{ok:true});
const user=auth(req);
if(req.method==='GET'&&p==='/profile'){const r=await sql`select id,username,role,display_name,created_at from users where id=${user.id}`;return json(res,200,{user:r[0]})}
if(req.method==='GET'&&p==='/dashboard'){const q=await sql`select count(*)::int n from questions`;const a=await sql`select count(*)::int n,coalesce(round(avg(score),1),0)::float avg from attempts where user_id=${user.id} and status='submitted'`;return json(res,200,{question_count:q[0].n,completed_attempts:a[0].n,average_score:a[0].avg})}
if(req.method==='GET'&&p==='/questions'){const teacher=user.role==='teacher';const r=await sql`select * from questions order by created_at desc`;return json(res,200,{questions:r.map(x=>publicQ(x,teacher))})}
if(req.method==='POST'&&p==='/questions'){if(user.role!=='teacher')return json(res,403,{error:'Khusus guru.'});const b=await body(req);const r=await sql`insert into questions(topic,level,question_text,options,answer_index,explanation,source,created_by) values(${b.topic||'Umum'},${b.level||'Lanjut'},${b.q},${JSON.stringify(b.opts||[])},${b.ans??0},${b.expl||''},${b.source||'Guru'},${user.id}) returning *`;return json(res,201,{question:publicQ(r[0],true)})}
if(req.method==='POST'&&p==='/questions/import'){if(user.role!=='teacher')return json(res,403,{error:'Khusus guru.'});const b=await body(req);let n=0;for(const x of (b.questions||[])){if(!x.q)continue;await sql`insert into questions(topic,level,question_text,options,answer_index,explanation,source,created_by) values(${x.topic||'Umum'},${x.level||'Lanjut'},${x.q},${JSON.stringify(x.opts||[])},${x.ans??0},${x.expl||''},${x.source||'Impor Guru'},${user.id})`;n++}return json(res,200,{inserted:n})}
if(req.method==='DELETE'&&p.startsWith('/questions/')){if(user.role!=='teacher')return json(res,403,{error:'Khusus guru.'});const id=p.split('/').pop();await sql`delete from questions where id=${id}`;return json(res,200,{ok:true})}
if(req.method==='POST'&&p==='/exams/quick-start'){if(user.role!=='student')return json(res,403,{error:'CBT siswa.'});const b=await body(req);let exam=await seedDefaultExam(user.id);let rows=await sql`select q.* from exam_questions eq join questions q on q.id=eq.question_id where eq.exam_id=${exam.id} order by random() limit ${Math.max(1,Math.min(50,Number(b.questionCount||exam.question_count)))}`;const ends=new Date(Date.now()+exam.duration_minutes*60000);const a=(await sql`insert into attempts(exam_id,user_id,ends_at) values(${exam.id},${user.id},${ends.toISOString()}) returning *`)[0];return json(res,200,{exam:{id:exam.id,title:exam.title,duration_minutes:exam.duration_minutes},attempt:{id:a.id,ends_at:a.ends_at,duration_seconds:exam.duration_minutes*60,answers:{}},questions:rows.map(x=>publicQ(x,false))})}
if(req.method==='PUT'&&p.match(/^\/attempts\/[^/]+\/answers$/)){const id=p.split('/')[2];const b=await body(req);const a=(await sql`select * from attempts where id=${id} and user_id=${user.id} and status='in_progress'`)[0];if(!a)return json(res,404,{error:'Attempt tidak ditemukan.'});if(new Date(a.ends_at)<=new Date())return json(res,409,{error:'Waktu ujian habis.'});const ans=b.answer===undefined?null:JSON.stringify(b.answer);await sql`insert into attempt_answers(attempt_id,question_id,answer) values(${id},${b.questionId},${ans}) on conflict(attempt_id,question_id) do update set answer=excluded.answer,saved_at=now()`;const rr=await sql`select question_id,answer,is_doubt from attempt_answers where attempt_id=${id}`;const answers={};for(const x of rr)answers[x.question_id]=x.answer;return json(res,200,{answers})}
if(req.method==='PUT'&&p.match(/^\/attempts\/[^/]+\/flag$/)){const id=p.split('/')[2];const b=await body(req);const a=(await sql`select * from attempts where id=${id} and user_id=${user.id} and status='in_progress'`)[0];if(!a)return json(res,404,{error:'Attempt tidak ditemukan.'});await sql`insert into attempt_answers(attempt_id,question_id,is_doubt) values(${id},${b.questionId},${!!b.doubt}) on conflict(attempt_id,question_id) do update set is_doubt=excluded.is_doubt,saved_at=now()`;const rr=await sql`select question_id,answer,is_doubt from attempt_answers where attempt_id=${id}`;const answers={};for(const x of rr)answers[x.question_id]=x.answer;return json(res,200,{doubt:!!b.doubt,answers})}
if(req.method==='POST'&&p.match(/^\/attempts\/[^/]+\/submit$/)){const id=p.split('/')[2];const a=(await sql`select a.*,e.title from attempts a join exams e on e.id=a.exam_id where a.id=${id} and a.user_id=${user.id} and a.status='in_progress'`)[0];if(!a)return json(res,404,{error:'Attempt tidak ditemukan atau sudah dikumpulkan.'});const rows=await sql`select q.id,q.answer_index,q.explanation,aa.answer from attempt_answers aa join questions q on q.id=aa.question_id where aa.attempt_id=${id}`;let correct=0;const review=[];for(const x of rows){let ans=x.answer;try{ans=JSON.parse(ans)}catch{};const ok=Array.isArray(ans)?ans.length===1&&ans[0]===x.answer_index:ans===x.answer_index; if(ok)correct++;review.push({correct:ok,explanation:x.explanation||''})}const total=(await sql`select count(*)::int n from exam_questions where exam_id=${a.exam_id}`)[0].n;const score=total?Math.round(correct/total*10000)/100:0;await sql`update attempts set status='submitted',submitted_at=now(),score=${score},correct_count=${correct} where id=${id}`;return json(res,200,{result:{score,correct,total},review})}
return json(res,404,{error:'Endpoint tidak ditemukan.'})}catch(e){console.error(e);return json(res,500,{error:e.message||'Internal server error'})}}
